# Generated by Django 5.1.4 on 2024-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_usersession_delete_sessiondata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomSessionStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
