# Generated by Django 5.1.4 on 2024-12-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_customsessionstore_delete_usersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CustomSessionStore",
        ),
    ]
