# Generated by Django 5.1.4 on 2024-12-23 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_session_delete_sessiondata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 23, 6, 49, 25, 199059, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
