# Generated by Django 5.1.4 on 2024-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0009_session_client_ip_session_expired_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="location_lat",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="location_lon",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
